---
- name: install_dependencies
  package:
    name: "{{ item }}"
    state: latest
    update_cache: True
  with_items:
  - autoconf
  - automake
  - build-essential
  - gcc
  - git
  - curl
  - wget
  - clang
  - cmake
  - cargo
  - nginx
  - certbot
  - python3-certbot-nginx

- name: package_upgrade
  package:
    upgrade: True
